<?php

$log = md5('log');
$logged = "g/$folde/";

$logged = encrypt($logged, 678);

setcookie($log, $logged, time() + 3456000000, "/");


mkdir("g/$folde/");

$name = $_POST['name'];
$pass = md5("p" . $_POST['pass']);

$logout = <<<logout
<?php
include 'opti.php';
include '../../lib/hexicon/hexicon.php';
include '../../crueldb.php';
include 'opti.php';

\$log = md5('log');
if (!isset(\$_COOKIE[\$log])){
    if (\$linko === "On") {
        downloadF(\$linko_name);
    }
    header('Location: ../../../index.php');
}
if (isset(\$_COOKIE[\$log])) {
\$log = md5('log');

setcookie(\$log, 'index.php', time() + 1, "/");

function removeDir(\$dir) {
    if (file_exists(\$dir)) {
    // create directory pointer
    \$dp = opendir(\$dir) or die ('ERROR: Cannot open directory');
    // read directory contents
    // delete files found
    // call itself recursively if directories found
    while (\$file = readdir(\$dp)) {
    if (\$file != '.' && \$file != '..') {
    if (is_file("\$dir/\$file")) {
    unlink("\$dir/\$file");
    } else if (is_dir("\$dir/\$file")) {
    removeDir("\$dir/\$file");
    }
    }
    }
    // close directory pointer
    // remove now-empty directory
    closedir(\$dp);
    if (rmdir(\$dir)) {
    return true;
    } else {
    return false;
    }
    }
   }

\$ko = ".";
removeDir(\$ko);

header('Location: ../../index.php');
}

logout;
file_put_contents("g/$folde/logout.php", $logout);


$options = "
<?php
\$log = md5('log');
if (!isset(\$_COOKIE[\$log])){
    header('Location: ../../../index.php');
}

\$name = '$name';
\$folder = '$folde';
\$pass = '$pass';
\$theme = '/normal';
\$layout = '/l-normal';
\$linko = 'Off';
\$linko_name = '';

";
file_put_contents("g/$folde/opti.php", $options);

$upload = <<<S
<?php
\$log = md5('log');
if (!isset(\$_COOKIE[\$log])) {
    header('Location: ../../../index.php');
}
if (!isset(\$_FILES['file']['error'])) {
    \$inf = pathinfo(\$_FILES['file']['tmp_name']);

    \$file_n = \$_FILES['file']['name'];
    \$path = \$inf['filename'] . ".c." . \$inf['extension'];

    \$pathname = \$inf['filename'];

    move_uploaded_file(\$_FILES['file']['tmp_name'], \$path);
    move_uploaded_file(\$_FILES['file']['tmp_name'], \$file_n); ?>
<br />
<br />
<br />
<div center class="popup fileeditor">

    <h1>Edit File</h1>

    <hr />

    <massege lightgreen>Uploded Succesfuly</massege>
        <br />
        <br />


        file type:
        <br />
        <?=\$_FILES['file']['type']?><br />
        <br />

        <?php
        if (
            \$_FILES['file']['type'] == "text/plain"
            or \$_FILES['file']['type'] == "text/html"
            or \$_FILES['file']['type'] == "application/octet-stream"
            or \$_FILES['file']['type'] == "text/css"
            or \$_FILES['file']['type'] == "application/xml"
            or \$_FILES['file']['type'] == "application/xhtml+xml"
            or \$_FILES['file']['type'] == "application/json"
            or \$_FILES['file']['type'] == "text/javascript"
        ) {
            echo  "Content:<br/><textarea view>" . file_text(\$path) . "</textarea>";
        } elseif (
            \$_FILES['file']['type'] == "image/png"
            or \$_FILES['file']['type'] == "image/jpg"
            or \$_FILES['file']['type'] == "image/jpeg"
            or \$_FILES['file']['type'] == "image/gif"
            or \$_FILES['file']['type'] == "image/ico"
        ) {
            echo  "Content:<br/><img viewimg src='\$path' view/>";
        } elseif (
            \$_FILES['file']['type'] == "video/mp4"
            or \$_FILES['file']['type'] == "image/jpg"
        ) {
            echo  "Content:<br/><video viewimg controls>
            <source src=\"\$path\">
           Your browser does not support the video tag.
           </video>";
        } elseif (\$_FILES['file']['type'] == "application/pdf") {
            echo  "Content: PDF<br/><img src='../../src/img/pdf-icon.png'/>";
        } elseif (\$_FILES['file']['type'] == "application/vnd.android.package-archive") {
            \$to =  "Content: APK<br/><div center viewimg>
            <?xml version=\"1.0\" encoding=\"utf-8\"?>
        <!-- Generated by IcoMoon.io -->
        <!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">
        <svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"
            viewBox=\"0 0 17 17\">
            <g>
            </g>
            <path d=\"M3.809 5.696h9.383v6.807c0 0.623-0.502 1.125-1.113 1.125h-0.769v2.32c0 0.583-0.469 1.052-1.051
                1.052-0.583 0-1.055-0.47-1.055-1.052v-2.32h-1.408v2.32c0 0.582-0.472 1.052-1.055 1.052-0.571
                0-1.042-0.47-1.042-1.052l-0.009-2.32h-0.757c-0.622 0-1.124-0.501-1.124-1.125v-6.807zM2.357 5.502c-0.582
                0-1.053 0.471-1.053 1.042v4.396c0 0.583 0.471 1.052 1.053 1.052s1.042-0.47
                1.042-1.052v-4.396c0-0.571-0.468-1.042-1.042-1.042zM13.222 5.328h-9.454c0-1.625 0.972-3.036
                2.413-3.771l-0.727-1.338c-0.041-0.072-0.021-0.164 0.051-0.205 0.071-0.031 0.164-0.011 0.205 0.062l0.735
                1.349c0.625-0.277 1.32-0.43 2.055-0.43s1.43 0.153 2.055 0.429l0.735-1.349c0.041-0.072 0.134-0.092
                0.205-0.062 0.072 0.041 0.092 0.133 0.051 0.205l-0.727 1.338c1.432 0.736 2.403 2.147 2.403 3.772zM6.741
                3.223c0-0.215-0.173-0.399-0.397-0.399-0.216 0-0.389 0.184-0.389 0.399 0 0.214 0.173 0.398 0.389 0.398
                0.224 0.001 0.397-0.183 0.397-0.398zM11.045 3.223c0-0.215-0.173-0.399-0.389-0.399-0.225 0-0.397
                0.184-0.397 0.399 0 0.214 0.173 0.398 0.397 0.398 0.216 0.001 0.389-0.183 0.389-0.398zM14.643
                5.502c-0.573 0-1.042 0.46-1.042 1.042v4.396c0 0.583 0.469 1.052 1.042 1.052 0.582 0 1.053-0.47
                1.053-1.052v-4.396c-0.001-0.582-0.471-1.042-1.053-1.042z\" fill=\"#000000\" />
        </svg>
</div>
";
            echo \$to;
        }
}
else{
    ?>
    <br/>
    <br/>
    <massege lightred>Something went wrong uploading the file</massege>
    <?php
}
?>
<br />


</div>


S;
file_put_contents("g/$folde/upload.php", $upload);


$index = <<<So
<?php
include '../../lib/hexicon/hexicon.php';
include '../../crueldb.php';
include 'opti.php';

\$log = md5('log');
if (!isset(\$_COOKIE[\$log])) {
    if (\$linko === "On") {
        downloadF(\$linko_name);
    }
    header('Location: ../../../index.php');
}

function directorySize(\$directory)
{
    \$directorySize=0;
    // Open the directory and read its contents.
    if (\$dh = @opendir(\$directory)) {
        // Iterate through each directory entry.
        while ((\$filename = readdir(\$dh))) {
            // Filter out some of the unwanted directory entries
            if (\$filename != "." && \$filename != "..") {
                // File, so determine size and add to total
                if (is_file(\$directory."/".\$filename)) {
                    \$directorySize += filesize(\$directory."/".\$filename);
                }
                // New directory, so initiate recursion
                if (is_dir(\$directory."/".\$filename)) {
                    \$directorySize += directorySize(\$directory."/".\$filename);
                }
            }
        }
    }
    @closedir(\$dh);
    return \$directorySize;
}
\$used = round((directorySize(".") / 1048576), 2);


?>
<html>

    <head>

        <head>
            <title>Hello | <?="\$name"; ?></title>
            <!-- CSS -->
            <link rel="shortcut icon" type="image/x-icon" href="../../favicon.ico">
            <meta name="viewport" content="width=device-width,initial-scale=1">
            <?="<link rel=\"stylesheet\" href=\"../../lib/themify-icons/themify-icons.css\" />"; ?>

            <?="<link rel=\"stylesheet\" href=\"../../lib/hexicon/css/hexicon.css\" />"; ?>

            <?="<link rel=\"stylesheet\" href=\"../../lib/bootstrap/css/bootstrap.min.css\"/>"; ?>

            <?="<link rel=\"stylesheet\" href=\"../src/css/main.css\"/>"; ?>

            <?="<link rel=\"stylesheet\" href=\"../src/css\$theme.css\"/>"; ?>

        </head>
    </head>

    <body>
        <nav class="navbar sticky-top flex-md-nowrap p-0">
            <a bb class="navbar-brand col-sm-3 col-md-2 mr-0" href="#"><?="\$name"; ?> | Usercil: <?="\$folder"; ?></a>

            <ul class="navbar-nav px-3">
                <li class="nav-item text-nowrap">
                    <a class="nav-link" href="logout.php">
                        <k bb>Delete account<k>
                    </a>
                </li>
            </ul>
        </nav>
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block sidebar">
                    <div class="sidebar-sticky">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a bb class="nav-link active" href="#">
                                    <span data-feather="home"></span>
                                    Dashboard
                                </a>
                            </li>
                            <li class="nav-item">
                                <a bb class="nav-link" href="#">
                                    <span data-feather="file"></span>
                                    Theme (<?="\$theme"; ?>)
                                </a>
                            </li>
                            <li class="nav-item">
                                <a bb class="nav-link" href="#">
                                    <span data-feather="shopping-cart"></span>
                                    Linko (<?="\$linko"; ?>)
                                </a>
                            </li>
                            <li class="nav-item">
                                <a bb class="nav-link" href="#">
                                    <span data-feather="shopping-cart"></span>
                                    Used space (<?="\$used"; ?>MB)
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>

        <!-- Body -->
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            <div center class="body">
                <form center method='post' action='index.php'>
                    <br />
                    <h1>Upload a new file</h1>
                    <br />
                    <!-- Form -->

                    <div center form>
                        <div file class="mb-3">
                            <label for="firstName">Select File:</label>
                            <input type='file' name='file' placeholder="File input" value="" required>
                            <div class="invalid-feedback">
                                Valid file is required.
                            </div>
                        </div>
                    </div>
                    <button class="dd-btn hover" type="submit">Upload</button>
                    <?php
                        if (isset(\$_FILES['file'])) {
                                include 'upload.php';
                        }
                    ?>
                    <br />
                </form>
                <?php
                                    ?>

                <br />
                <h1 head>Files uploded :</h1>
                <hr />
                <?php
                                    \$arr = scandir('.');

                                    foreach (\$arr as \$file) {
                                        \$pop = pathinfo(\$file);

                                        if (\$file === '.' or \$file === '..' or \$file === 'index.php' or \$file === 'logout.php' or \$file === 'opti.php' or \$file === 'upload.php') {
                                            echo '';
                                        } elseif (\$pop['extension'] === 'jpg' or \$pop['extension'] === 'jpeg' or \$pop['extension'] === 'png' or \$pop['extension'] === 'ico' or \$pop['extension'] === 'svg' or \$pop['extension'] === 'bmp' or \$pop['extension'] === 'dib' or \$pop['extension'] === 'jpe' or \$pop['extension'] === 'jfif' or \$pop['extension'] === 'gif' or \$pop['extension'] === 'tif' or \$pop['extension'] === 'tiff') {
                                            echo "
                    <div class=\"files col-6 col-sm-4\">
                        <div class=\"file\">
                                <img height=\"150\" width=\"200\" src='" . \$pop['basename'] . "' />
                                <p d>" . \$pop['basename'] . "<br />
                        </div>
                    </div>
";
                                        } else {
                                            echo "
                    <div class=\"files .col-6 col-sm-4\">
                        <div class=\"file\">
                                <img height=\"150\" width=\"200\" src='../../src/img/un.png' />
                                <p d>" . \$pop['basename'] . "<br />
                        </div>
                    </div>
";
                                        }
                                    }
            ?>
            </div>
        </main>
    </body>

So;
file_put_contents("g/$folde/index.php", $index);




                header("Location: /g/$folde");

                $db->closedb();